// <auto-generated />
using System;
using AIKOCLUK.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIKOCLUK.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921004020_AddAiAdviceHistoryTables")]
    partial class AddAiAdviceHistoryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AIKOCLUK.Models.AiAdviceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenelDegerlendirme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HaftalikOdakTavsiyesi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KirmiziAlarmDersleri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AiAdviceHistories");
                });

            modelBuilder.Entity("AIKOCLUK.Models.AiFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedSentiment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedAdvice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("AiFeedbacks");
                });

            modelBuilder.Entity("AIKOCLUK.Models.AiTargetSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AiAdviceHistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Neden")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Taktik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AiAdviceHistoryId");

                    b.ToTable("AiTargetSubjects");
                });

            modelBuilder.Entity("AIKOCLUK.Models.ExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MathNet")
                        .HasColumnType("REAL");

                    b.Property<double>("ScienceNet")
                        .HasColumnType("REAL");

                    b.Property<double>("SocialNet")
                        .HasColumnType("REAL");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TimeManagementIssue")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TurkishNet")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("AIKOCLUK.Models.ExamTopicError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlankCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExamResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncorrectCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamResultId");

                    b.ToTable("ExamTopicErrors");
                });

            modelBuilder.Entity("AIKOCLUK.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStressLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyAvailableStudyHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDepartment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUniversity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeakSubjects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AIKOCLUK.Models.AiFeedback", b =>
                {
                    b.HasOne("AIKOCLUK.Models.Student", "Student")
                        .WithMany("AiFeedbacks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AIKOCLUK.Models.AiTargetSubject", b =>
                {
                    b.HasOne("AIKOCLUK.Models.AiAdviceHistory", null)
                        .WithMany("HedefKonular")
                        .HasForeignKey("AiAdviceHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIKOCLUK.Models.ExamResult", b =>
                {
                    b.HasOne("AIKOCLUK.Models.Student", "Student")
                        .WithMany("ExamResults")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AIKOCLUK.Models.ExamTopicError", b =>
                {
                    b.HasOne("AIKOCLUK.Models.ExamResult", "ExamResult")
                        .WithMany("TopicErrors")
                        .HasForeignKey("ExamResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamResult");
                });

            modelBuilder.Entity("AIKOCLUK.Models.AiAdviceHistory", b =>
                {
                    b.Navigation("HedefKonular");
                });

            modelBuilder.Entity("AIKOCLUK.Models.ExamResult", b =>
                {
                    b.Navigation("TopicErrors");
                });

            modelBuilder.Entity("AIKOCLUK.Models.Student", b =>
                {
                    b.Navigation("AiFeedbacks");

                    b.Navigation("ExamResults");
                });
#pragma warning restore 612, 618
        }
    }
}
