// <auto-generated />
using System;
using AIKOCLUK.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIKOCLUK.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AIKOCLUK.Models.AiFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedSentiment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedAdvice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("AiFeedbacks");
                });

            modelBuilder.Entity("AIKOCLUK.Models.ExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MathNet")
                        .HasColumnType("REAL");

                    b.Property<double>("ScienceNet")
                        .HasColumnType("REAL");

                    b.Property<double>("SocialNet")
                        .HasColumnType("REAL");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TimeManagementIssue")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TurkishNet")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("AIKOCLUK.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStressLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyAvailableStudyHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDepartment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUniversity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeakSubjects")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AIKOCLUK.Models.AiFeedback", b =>
                {
                    b.HasOne("AIKOCLUK.Models.Student", "Student")
                        .WithMany("AiFeedbacks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AIKOCLUK.Models.ExamResult", b =>
                {
                    b.HasOne("AIKOCLUK.Models.Student", "Student")
                        .WithMany("ExamResults")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AIKOCLUK.Models.Student", b =>
                {
                    b.Navigation("AiFeedbacks");

                    b.Navigation("ExamResults");
                });
#pragma warning restore 612, 618
        }
    }
}
